# Generated by Django 4.0.4 on 2022-05-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_name_duties_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='duties',
            name='job',
        ),
        migrations.AddField(
            model_name='duties',
            name='job',
            field=models.ManyToManyField(to='resume.experience'),
        ),
        migrations.AlterField(
            model_name='duties',
            name='short_description',
            field=models.CharField(default='duty description', max_length=50),
        ),
    ]
