# Generated by Django 4.0.4 on 2022-05-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_blurb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['level'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
