# Generated by Django 4.0.4 on 2022-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_blurb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['level'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='duties',
            name='order',
            field=models.IntegerField(default=5),
        ),
    ]
