# Generated by Django 4.0.4 on 2022-05-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['date']},
        ),
    ]
