# Generated by Django 4.0.4 on 2022-05-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_degree_options_alter_duties_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duties',
            options={'ordering': ['list_order'], 'verbose_name': 'Duty', 'verbose_name_plural': 'Duties'},
        ),
        migrations.RenameField(
            model_name='duties',
            old_name='order',
            new_name='list_order',
        ),
    ]
