# Generated by Django 4.0.4 on 2022-05-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_skill_options_duties_order'),
        ('resume', '0011_alter_certificate_options_alter_degree_options'),
    ]

    operations = [
    ]
