# Generated by Django 4.0.4 on 2022-05-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_merge_20220524_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='duties',
            options={'ordering': ['order'], 'verbose_name': 'Duty', 'verbose_name_plural': 'Duties'},
        ),
        migrations.RemoveField(
            model_name='duties',
            name='list_order',
        ),
    ]
